### ISSUE TITLE
R2D2_v3 Adaptation and Observation Database Development

### ISSUE THREAD

**Issue by Dooruk** [GEOS-ESM/swell#318]
This issue will evolve over time and there will be new steps/issues introduced.
**Feel free to add and/or suggest edits any time. Most of these tasks will involve other GMAO folks.**

# Which files need to be indexed by R2D2 v3: 

These files are currently located in `/discover/nobackup/projects/gmao/advda/R2D2DataStore/Shared`:

### 1) Observations (IODAv3 format also BUFR format for the future):

⚠  Currently, all observations are organized in `PT6H` windows.

  - For `geos_atmosphere` we are using `x0050`:
    - [x] **ncdiag**: These are files which were created by running `convert_ncdiags` suite. 

For atmosphere, at the moment we rely upon previous x00* experiment runs, i.e. phase 1. See Phase 1 and other phases in figure at the bottom of this issue.

   - For `geos_marine`, there are two sources, **the tiered CI tests only use a subset** of these:
     - [x] **odas**: These are local GMAO processed files (**O**cean **DA** **S**ystem)
     - [x] **gdas_marine**: These are the files that are transferred from NOAA/EMC.

### 2)  Bias Coefficients (BCs) (only relevant for `geos_atmosphere`):
  - [ ] **gsi**: These are files which were created by running `convert_ncdiags` suite and `x0050` experiment. Has five different file types:
    - tlapse (txt)
    - satbias (nc4) (Satellite Bias)
    - satbias_cov (nc4) (Satellite Bias)
    - acftbias (nc4) (Aircraft)
    - acftbias_cov (nc4) (Aircraft)

### 3) Experiment Background (only relevant for `geos_marine`):
`geos_atmosphere` uses `GetBackgroundGeosExperiment` task now, used to utilize `geos` folder. 
`geos_marine` utilizes `mom6_cice6_UFS` folder.
### 4) [currently inactive] Ensemble files:
 (currently **none** for either model. `geos_atmosphere` uses `GetEnsembleGeosExperiment`)

---
# Needs from R2D2: 

### Immediate term:

- [x] Indexing `geos_atmosphere` and `geos_marine` `IODAv3` observations that SWELL utilizes within the new R2D2_v3 API context and testing the `search` functionality. 

(dated `20231010T000000Z`, `20231010T060000Z` for `geos_atmosphere`) 
(dated `20210701`, `20210702` for `geos_marine`) 

- [ ] Implementing the new R2D2_v3 API within Swell

### Short-term:
- Index more observations from the x0050 period for `geos_atmosphere`. which ideally consists of two seasons. (Late summer/Fall 2023). 
- Some obs yamls might require fewer changes (`CRIS`) whereas some of them need to be created from "scratch" (`OMPS`).
- Implement R2D2 indexing for a few days and test DA cycling

### (Ignore this for now) Long-term needs/thoughts:
- Current GEOS FP dataset consists of `bufr` and `nc` files which are not in `IODAv3` format, this conversions has to take place.
- Devise a `BUFR-to-IODAv3` conversion approach, employ some of the existing EMC methods (?), multiple options here:
  - The backend approach within JEDI (by defining the `engine: type`)
  - On-the fly conversion
  - Offline conversion (will create file duplicates)
- Processing bufr files via GEOS backgrounds 
- How to ensure GSI filters (thinning) are maintained while we use the backend conversions.
- Devise a `nc-to-IODAv3` conversion approach (same as above, could be done online or offline) 
- Some of these conversions might split observations into multiple files, will that create a problem (metop/mtiasi) ?
- Identify additional `ioda-conv` needs for different types of observation types, for both atmosphere and ocean (e.g., `mls_nrt` converter is not available).
- Observation files version information (?)
- VarBC handling via R2D2 (?)
- (Ideally before the year 2100) Full GEOS FP (multi-month, multi-year) dataset

FYI @ashiklom 

## Detailed phases on atmosphere observations
`geos_atmosphere` observation processing plan:

<p align="center">
<img width="513" alt="Image" src="https://github.com/user-attachments/assets/9ffc3b38-f52e-4036-b32e-a4dd4929660e" />
</p>

More details on this: https://github.com/GEOS-ESM/swell/issues/378

**Comment by rtodling** [comment]
Doruk, thanks for these items. I would remove the stuff about geovals. When dealing w/ the real (raw) obs, geovals is non-existent - it doesn't matter how longer it takes (it simply N/A).

**Comment by Dooruk** [comment]
> Doruk, thanks for these items. I would remove the stuff about geovals. When dealing w/ the real (raw) obs, geovals is non-existent - it doesn't matter how longer it takes (it simply N/A).

Thanks, made the change.
