### ISSUE TITLE
BUFR2IODA Conversion

### ISSUE THREAD

**Issue by Dooruk** [GEOS-ESM/swell#378]
The following lays out steps required for us to incorporate the capabilities of having swell convert bufr files to IODA on the fly. This is an edited version of the original written by @Dooruk. I will try to put some names around the items below to sort of give an idea of who might be best to work on a given item, but please take those as suggested names. If anyone feels that's not quite something within their realm, no problem, just let us know.

- [x] GEOSadas: move obsys.rc to sidb in mksi (Ricardo) - GEOS_mksi tag: g5.41.2
- [x] GEOSadas: pull acquire applications into a repo of their own - see below (Ricardo)
- [x] SWELL needs to learn how to extract the obs classes available and applicable to a given cycle time; that is, given a set of obs-classes, SWELL should read from the present databased (obsys.rc), extract the class of interest, see if data is available for the date/time of request, and create a list of fully resolve file names from the database that can then be passed on the either (or both) of the step below. (Ricardo) - Akira and R had a conversation about this. R will bring the GEOSDAS machinery to bring observations into the run experiment given a series of obsclass, a date and a couple of other parameters. This capability is based on a series of Perl scripts; they will require the installation in SWELL to know than simply handling Python scripts. I will need to work with Michael and Alexey on this. The command line to bring in data into the run env of converter suite will be as simple as the following:

`acquire_obsys -v -d $FVWORK -s $SPOOL -la $nlook -ssh  \
                 -strict $nymd $nhms $nfreq $nstep $OBSCLASS
`

where OBSCLASS defines the classes, as for example: disc_airs_bufr,disc_amsua_bufr,gmao_amsr2_bufr
nymd and nhms are the GEOS convention for 8-digit date and 6-digit time, and I will explain the other variables when I add the PR to that will allow swell to pull the required codes the an adequate ESM-repo (see https://github.com/GEOS-ESM/swell/pull/498)

To be more specific about how this can be exercised in SWELL, I am inserting here an set of c-sh lines (that can be placed in a file and turned into an executable shell program - this illustrates how to actually use the command line above. The only parameters that need to be dealt with in a swell context are the env variables used in the c-sh script below and the date and time parameters: nymd, nhms - everthing else can (for the time being) be wired w/o loss of functionality:

`#!/bin/csh

source /discover/nobackup/projects/gmao/advda/swell/JediBundles/fv3_soca_SLES15/build-intel-release/modules

setenv SWELLEXP /discover/nobackup/rtodling/SwellExperiments/SLES15/swell-3dfgat_x50/
setenv SATBFRDB $SWELLEXP/GEOS_mksi/ObsClass/
setenv MYEXP /gpfsm/dnb05/projects/p139/rtodling/TEST/GETBUFR/

setenv WORK $MYEXP/work
setenv SPOOL $MYEXP/spool

setenv OBSCLASS "disc_airs_bufr,disc_amsua_bufr,gmao_amsr2_bufr,gmao_gmi_bufr,mls_nrt_nc,ncep_1bamua_bufr,ncep_acftpfl_bufr,ncep_atms_bufr,ncep_aura_omi_bufr,ncep_avcsam_bufr,ncep_avcspm_bufr,ncep_crisfsr_bufr,ncep_goesfv_bufr,ncep_gpsro_bufr,ncep_mhs_bufr,ncep_mtiasi_bufr,ncep_prep_bufr,ncep_satwnd_bufr,ncep_ssmis_bufr,ncep_tcvitals,npp_ompsnm_bufr,r21c_npp_ompslp_nc,m2scr_n21_ompslp_nc,gmao_mlst_bufr"

set path = ( . ~/.local/bin/ $path )

if (! -d $WORK ) mkdir -p $MYWORK

/bin/cp $SATBFRDB/obsys-nccs.rc obsys.rc

set nymd = 20231010
set nhms = 120000
acquire_obsys -v -d $WORK -s $SPOOL -strict \
     -ssh $nymd $nhms 060000 1 $OBSCLASS`

The software needed to allow swell to invoke a command line similar to what's written about has now been extract from GEOS and placed in a repo of its own:  https://github.com/GEOS-ESM/GMAO_perllib  ; SWELL needs to be modified to:

- [x] when cloned, also clone GMAO_perllib  - please do not pull develop/main, the following tag should be used: g1.0.1
- [x] when installed, also install GMAO_perilib (see CMakelist in GMAO_perllib to see how files and programs need to fall into the bin directory; notice that with this, SWELL will need to be extended to learn to install things that are not python. I don't know pip very well, but I believe  that is a python-centric and therefore, I believe the install procedures of SWELL will need to be generalized.

There are two options to implement the converters:

### 1. **Offline converter**: once SWELL the steps above are complete:

- [x] #454

- [x] build infrastructure in SWELL to process (go over) each of the files in the list created above, and apply the corresponding converter. In some case, as I understand, the convert program will be different (GPSRO seems to be a case in point), so SWELL will need to know which application to call for a given class.  (Seth, Akira, Doruk, Others could contribute to this, esp in the arrangement of yamls.)

- [ ] [OBS team] the conversion should try to create IODA files in the form presently created by ncdiag2ioda; this might be a little trick for conventional (prepbfr) data, but it seems doable. (we can ALL think together about this)

- [ ] There could be a suite in SWELL associated with the converter with the function of populating R2D2 once the converted files are available; this could be a suite ran only by a few people (those w/ the ability to write in R2D2) - or, for testing purposes, a user should be able to create its own temperature R2D2 to live somewhere under its own file systems). (Alexey, Doruk, Seth, ?)

- [ ] the converter step should also be an option implemented within the Var suites so that these could, in principle, process data that might not have been process and put in R2D2. (Ricardo, Doruk, Alexey)

- [ ] The part that puts together the observation yamls, to make up the final (Var) yaml, will need to be adapted to include data thinning, super-obbing, additional QC; whatever needs to be done w/ the data before the HOFX sees the data. Ideally these will be a separate set of yaml files associated w/ each ob-space that is handled by SWELL as it comes up w/ the final yaml. 

### 2. **Online converter**: 

This is a set that would bypass the creation of the IODA files (converted from bufr), allowing the Var to run directly from the original bufr files. This might be a good option for operations, to avoid the cost of reading the data twice. This should be relatively simple to put together once the steps above for the offline processing have been completed. I will suggest postponing this one until we gather some experience and get meaningful results running w/ what the offline procedures will generate.

I think some of the stuff below this line is outdated ... @cohen-seth has made considerable progress processing various data classes. I'll leave it up to others to edit/update/remove.

**Comment by cohen-seth** [comment]
# OUTDATED as of 5/06/2026 because bufr2ioda.x is deprecated


### Bufr to Ioda conversion tests results (offline):

The only changes needed were to change the paths in the **input** and **output** lines in the existing yaml files (test folder). 


<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:////Users/sicohen/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip.htm">
<link rel=File-List
href="file:////Users/sicohen/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip_filelist.xml">

</head>

<body link="#467886" vlink="#96607D">


classes | converter | yaml | result |  
-- | -- | -- | -- | --
1bmhs | bufr2ioda.x | bufr_ncep_1bmhs.yaml | successful | ✅
amsua | bufr2ioda.x | bufr_ncep_1bamua_n15.yaml | successful | ✅
amsua | bufr2ioda.x | bufr_ncep_1bamua_ta.yaml | successful | ✅
atms | bufr2ioda.x | bufr_ncep_atms.yaml | successful | ✅
mtiasi | bufr2ioda.x | bufr_ncep_mtiasi.yaml | successful | ✅
satwind (am & pm) | bufr2ioda.x | bufr_ncep_satwind_avhrr.yaml | successful | ✅
aircft | bufr2ioda.x | bufr_ncep_prepbufr_aircft.yaml | successful | ✅
sevcsr | bufr2ioda.x | bufr_ncep_sevcsr.yaml | successful | ✅



</body>

</html>

**Comment by cohen-seth** [comment]
## From convert_bufr update: bufr-query bufr2netcdf.x #741 

### Description

Updated 05-06-2026:

Log edits and error handling cleanup

Ouptut ioda files now have sat_name and satid in the file name (e.g., `cosmic2_755`)

File Cleanup: convert_bufr will now remove the leftover 'temporary*.nc' files that don't get renamed due to an existing converted file for that obstype date 

To Do:

1. Add override option to overwrite existing files 
2. Make edits that use swell utilities 
	- clean_cycle
3. Only convert files for obs types in the experiment yaml. Currently tries to convert all the bufr  files it finds in the cylce directory

___  
Updating the `bufr_to_ioda.py` task from the convert_bufr suite to use the new executable `bufr2netcdf.x` from `bufr-query`. The previous executable `bufr2ioda.x` is deprecated.   `bufr2netcdf.x`  and  `bufr2ioda.x` each require a specific yaml file format so a new yaml directory was added for the  `bufr2netcdf.x` specific yamls for all SPOC yamls (https://github.com/NOAA-EMC/spoc/tree/develop/dump/config/atmosphere). 

Produces one file for each satid ('{splits/satd}' method).

The key changes to `bufr_to_ioda.py` were:
- removing steps for ***generating*** the mapping yamls (the older method changed the actual contents of the yaml files)
- changes to account for the (full) CLI command changing from `bufr2ioda.x [bufr file] [bufr_mapping.yaml]` to `bufr2netcdf.x [bufr file] [bufr_mapping.yaml]`
- added observations type to the defaults in the `convert_bufr/suite_config.py` and question defaults
 - bufr_to_ioda.py executable changed from bufr2ioda.x (deprecate) to bufr2netcdf.x
 - New yaml files with format specific to bufr2netcdf.x added to new directory in  `configuration/jedi/bufr2ioda/bufr2netcdf_x/` 
 - Working for multiple observation types
 

## Impact

Should make the next set of changes easier if/when we integrate the use of the `bufr-query` `ObsBuilder`


## Testing


# Swell  SPOC yaml testing convert_bufr

| yaml | tested | working | questions_default | compared against other nc4 outside swell | Notes |
| :--- | :---: | :---: | :---: | :---: | :--- |
| `spoc_prepbufr_aircraft.yaml` | 🛑 | TBD | | | Requires the custom naming structure check (`acft_profiles`). | |
| `spoc_radiance_1bamua.yaml` | ✅ | ✅ | * | |
| `spoc_radiance_1bmhs.yaml` | ✅ | ✅ | * | |
| `spoc_radiance_amsr2.yaml` | | | | |
| `spoc_radiance_amsua_1bamua.yaml` | 🛑 | | | |
| `spoc_radiance_amsua_esamua.yaml` | | | | |
| `spoc_radiance_atms.yaml` | ✅ | ✅ | *| |
| `spoc_radiance_avcsam.yaml` |✅ |✅ |* | |
| `spoc_radiance_avcspm.yaml` | ✅ | ✅ | * |  |
| `spoc_radiance_avhrr.yaml` | ✅ | 🛑✅  | | | Used for BOTH avcsam/avcspm conversions. |
| `spoc_radiance_cris-fsr.yaml` | 🛑 | | | |
| `spoc_radiance_gmi.yaml` | | | | |
| `spoc_radiance_gpsro.yaml`  | ✅ | ✅ | * | | Ran successfully in previous log output (created files for metop, cosmic2, planetiq, etc.). |  |
| `spoc_radiance_iasi.yaml` | 🛑 | | | | Note: Dict has both `spoc_radiance_mtiasi.yaml` and `spoc_radiance_iasi.yaml` mapped to mtiasi obs. |
| `spoc_radiance_mhs_1bmhs.yaml` | 🛑 | | |  |
| `spoc_radiance_mtiasi.yaml` | ✅ | ✅ | | |
| `spoc_radiance_ssmis.yaml` | ✅ | ✅ | | |
| `spoc_retrieval_ozone_omi.yaml` | | | | |
| `spoc_retrieval_ozone_ompslp.yaml` | | | | |
| `spoc_retrieval_ozone_ompstc.yaml` | | | | |
