### ISSUE TITLE
(SE) Utilizing more Cylc features

### ISSUE THREAD

**Issue by Dooruk** [GEOS-ESM/swell#490]
One of the main reasons we use Cylc is its design which includes many useful features for DA cycling. We currently exercise some of them but we should take advantage of more. I will create this as an epic and as users think of more features they can add this can expand.

## Necessary ones:

- [ ] **Execute certain tasks in TSE staging area:** This would mainly be relevant for GEOS simulations but if it provides significant efficiency for others we could benefit from it.
- [ ] **Use compiler flags for different environments:** For compute performance we should use certain flags (compiler and node type dependent), an example for Intel below:

``` bash
setenv I_MPI_FABRICS shm:ofi
setenv I_MPI_OFI_PROVIDER psm3
```
From Matt: The latter is required for Intel MPI on the Milan nodes. the former is good to use well.

- [ ] **Hold before certain tasks:** @rtodling mentioned this one. The ability for a suite to "hold" before a certain task, say `RunJediVarExecutable` so that different configurations could be tested swiftly without the need to `swell create` a whole new suite. JCSDA's https://github.com/JCSDA-internal/skylab uses this feature in a different workflow engine called EWOK.
- [x] **Restart a failed suite from a certain cycle & task:** This one is straightforward with using TUI. Involves using reinstall-reload function. I will add this to the documentation.

## Optional but useful ones:

- [ ] Cylc 8.5.0 has an option to use external editors to view log files, that is a great feature:
https://cylc.discourse.group/t/tip-cylc-tui-external-log-viewer/1236

- [ ] Workflow [sending email](https://cylc.github.io/cylc-doc/stable/html/tutorial/furthertopics/message-triggers.html) if suite stops/fails. I was able to do this with a sandbox Cylc setup.
- [ ] Failed `gmao_ci` workflows posting `job.err` and `job.out` somewhere on git for identifying the problem.
- [ ] **Using more SLURM and Milan node features**:
   - [ ]  **Assign different walltime for tasks:** Default is 1hr but most tasks take less than this, which could improve queue times. 
   - [ ] **Shared nodes:** Milan nodes has a feature to share nodes between users, for low demand jobs this could save queue time.
   - [x] **Per-host:** Not sure about this one, @rtodling uses it, relevant for compute performance.

**Comment by Dooruk** [comment]
Case in point for retrying, the task had SLURM issues (pink square) but now running after two failed attempts and with zero changes. I just happened to be monitoring:

<img width="374" alt="Screenshot 2024-12-20 at 1 40 56 PM" src="https://github.com/user-attachments/assets/aaaca3a4-22af-413d-ab2d-29cc93386599" />

**Comment by ashiklom** [comment]
For retrying tasks: As a first pass, this can be added directly to the cylc task configurations.

https://cylc.github.io/cylc-doc/stable/html/user-guide/writing-workflows/runtime.html#task-retry-on-failure
