### ISSUE TITLE
Develop the observation operator configuration YAML

### ISSUE THREAD

**Issue by danholdaway** [GEOS-ESM/swell#58]
### AMSUA:

- [ ] Snow over ice is incorrect in the GeoVaLs. This is due to the missing values (large positive number) being used instead of not being used over the ocean/sea ice.
- [ ] Fixed surface GeoVaLs in fv3-jedi differ significantly from GSI GeoVaLs
- [ ] FV3-JEDI lacks a land mask for interpolation. 
- [ ] EMC noted peculiarity in the omb JEDI - omb GSI map plots.

### IASI

- [x] Bugs found in UFO filter code (https://github.com/GEOS-ESM/swell/issues/68#issuecomment-1150185220)

### Sondes

- [ ] Insufficient metadata in the observation files.

### Ozone

- [X] GSI does not output sensible GeoVaLs so running the UFO tests will be skipped.

**Comment by danholdaway** [comment]
@CoryMartin-NOAA we will try to use the EPIC to document any global issues that we find with the instruments. Hopefully you see this tagging.
